name: script-kcl
on: push

jobs:
  check-macos:
    strategy:
      matrix:
        os: [macos-13, macos-13-xlarge, macos-14, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Check Install Script CLI
        run: curl -fsSL https://kcl-lang.io/script/install-cli.sh | /bin/bash
      - name: Check KCL run
        shell: bash -leo pipefail {0}
        run: sudo kcl version && sudo kcl run ./examples/configuration/nginx.k

      - uses: actions/setup-go@v1
        with:
          go-version: "1.22"

      - name: Check Go Installation
        run: go install kcl-lang.io/cli/cmd/kcl@main && sudo $HOME/go/bin/kcl version && sudo $HOME/go/bin/kcl run ./examples/configuration/nginx.k

      - name: Check Uninstall Script CLI
        run: curl -fsSL https://kcl-lang.io/script/uninstall-cli.sh | /bin/bash

  check-linux:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Check Install Script CLI
        run: wget -q https://kcl-lang.io/script/install-cli.sh -O - | /bin/bash
      - name: Check KCL run
        shell: bash -ieo pipefail {0}
        run: |
          kcl version
          kcl run ./examples/configuration/nginx.k

      - uses: actions/setup-go@v1
        with:
          go-version: "1.22"

      - name: Check Go Installation
        run: go install kcl-lang.io/cli/cmd/kcl@main && sudo $HOME/go/bin/kcl version && sudo $HOME/go/bin/kcl run ./examples/configuration/nginx.k

      - name: Check Uninstall Script CLI
        run: wget -q https://kcl-lang.io/script/uninstall-cli.sh -O - | /bin/bash

  check-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check Install Script CLI
        run: powershell -Command "iwr -useb https://www.kcl-lang.io/script/install-cli.ps1 | iex"

      - name: Check KCL run
        run: C:\kclvm\bin\kcl.exe run ./examples/configuration/nginx.k

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"

      - name: Check Go Installation
        run: go install kcl-lang.io/cli/cmd/kcl@main && C:\Users\runneradmin\go\bin\kcl.exe run ./examples/configuration/nginx.k

      - name: Check Uninstall Script CLI
        run: powershell -Command "iwr -useb https://www.kcl-lang.io/script/uninstall-cli.ps1 | iex"

  check-kcl-scoop-install:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Scoop Install
        shell: powershell
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop bucket add kcl-lang https://github.com/kcl-lang/scoop-bucket.git
          scoop install kcl-lang/kcl
          kcl.exe ./examples/configuration/nginx.k

  check-kcl-brew-install:
    strategy:
      matrix:
        os: [macos-13, macos-latest, ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master

      - name: Check Brew Installation
        working-directory: .
        run: |
          brew install kcl-lang/tap/kcl
          echo "brew installed successfully"
          kcl version
          kcl ./examples/configuration/nginx.k
          brew uninstall kcl-lang/tap/kcl
          brew uninstall kcl-lang/tap/kcl-lsp
