name: script-kusion
on:
  push:
    branches: 
     - main
jobs:
  check-kusion-script-install:
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Check Install Script
        run: |
          static/script/install.sh
          curl -fsSL https://kusionstack.io/scripts/install-kusion.sh | /bin/bash
      - name: Check Kusion run
        shell: bash -leo pipefail {0}
        run: |
          sudo kcl -Y static/stack/kcl.yaml
          sudo kusion version
          sudo kusion compile -w static/stack -o stdout
          cd static/stack && sudo kusion compile

  check-kusion-brew-install:
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - name: Check Brew Installation
        working-directory: .
        run: |
          brew install KusionStack/tap/kusion
          echo "brew installed successfully"
          kusion version
          kusion compile -w static/stack -o stdout
          cd static/stack && kusion compile

  check-kusion-go-install:
    strategy:
      matrix:
        os: [macos-11, macos-12, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-go@v1
        with:
          go-version: "1.19"

      - name: Check Go Installation
        working-directory: .
        run: |
          go install kusionstack.io/kusion@main
          echo "go installed successfully"
          $HOME/go/bin/kusion version
          $HOME/go/bin/kusion compile -w static/stack -o stdout
          cd static/stack && $HOME/go/bin/kusion compile
