name: script-kcl
on:
  push:
    branches: 
     - main
jobs:
  check-macos:
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Check Install Script Core
        run: static/script/install.sh

      - name: Check Install Script CLI
        run: static/script/install-cli.sh
      - name: Check KCL run
        shell: bash -leo pipefail {0}
        run: sudo kcl version && sudo kcl run ./static/stack/main.k

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-go@v1
        with:
          go-version: "1.21"

      - name: Check Python Installation
        run: python3 -m pip install kclvm --user -U && python3 -m kclvm ./static/stack/main.k

      - name: Check Go Installation
        run: go install kcl-lang.io/cli/cmd/kcl@main && sudo $HOME/go/bin/kcl version && sudo $HOME/go/bin/kcl run ./static/stack/main.k

      - name: Check Uninstall Script CLI
        run: static/script/uninstall-cli.sh


  check-linux:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Check Install Script Core
        run: static/script/install.sh

      - name: Check Install Script CLI
        run: static/script/install-cli.sh
      - name: Check KCL run
        shell: bash -ieo pipefail {0}
        run: |
          kcl version
          kcl run ./static/stack/main.k

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-go@v1
        with:
          go-version: "1.21"

      - name: Check Python Installation
        run: python3 -m pip install kclvm --user -U && python3 -m kclvm ./static/stack/main.k

      - name: Check Go Installation
        run: go install kcl-lang.io/cli/cmd/kcl@main && sudo $HOME/go/bin/kcl version && sudo $HOME/go/bin/kcl run ./static/stack/main.k

      - name: Check Uninstall Script CLI
        run: static/script/uninstall-cli.sh

  check-windows:
    strategy:
      matrix:
        goversion: ['1.20', '1.21']
        pyversion: ['3.9', '3.10']
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Install Script Core
        run: static/script/install.ps1

      - name: Check Install Script CLI
        run: static/script/install-cli.ps1
      - name: Check KCL run
        run: C:\kclvm\bin\kcl.exe run ./static/stack/main.k

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.goversion }}

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.pyversion }}

      - name: Check Python Installation
        run: python3 -m pip install kclvm --user -U && python3 -m kclvm ./static/stack/main.k

      - name: Check Go Installation
        run: go install kcl-lang.io/cli/cmd/kcl@main && C:\Users\runneradmin\go\bin\kcl.exe run ./static/stack/main.k

      - name: Check Uninstall Script CLI
        run: static/script/uninstall-cli.ps1

  check-kcl-scoop-install:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Scoop Install
        shell: powershell
        run: |
          iwr -useb get.scoop.sh -outfile 'install.ps1'
          .\install.ps1 -RunAsAdmin
          scoop bucket add kcl-lang https://github.com/kcl-lang/scoop-bucket.git
          scoop install kcl-lang/kcl
          kcl.exe ./static/stack/main.k

  check-kcl-brew-install:
    strategy:
      matrix:
        os: [macos-11, macos-12, macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: Homebrew/actions/setup-homebrew@master

      - name: Check Brew Installation
        working-directory: .
        run: |
          brew install kcl-lang/tap/kcl
          echo "brew installed successfully"
          kcl version
          kcl ./static/stack/main.k
          brew uninstall kcl-lang/tap/kcl
          brew uninstall kcl-lang/tap/kcl-lsp

          brew install kcl-lang/tap/kcl@0.7.0
          echo "brew installed successfully"
          kcl version
          kcl ./static/stack/main.k
          brew uninstall kcl-lang/tap/kcl@0.7.0

          brew install kcl-lang/tap/kcl@0.8.0
          echo "brew installed successfully"
          kcl version
          kcl ./static/stack/main.k
          kcl-language-server version
          brew uninstall kcl-lang/tap/kcl@0.8.0
          brew uninstall kcl-lang/tap/kcl-lsp@0.8.0

          brew install kcl-lang/tap/kcl-lsp
          brew uninstall kcl-lang/tap/kcl-lsp
          brew install kcl-lang/tap/kcl-lsp@0.7.0
          brew uninstall kcl-lang/tap/kcl-lsp@0.7.0
          brew install kcl-lang/tap/kcl-lsp@0.8.0
          kcl-language-server version
          brew uninstall kcl-lang/tap/kcl-lsp@0.8.0
