name: script
on:
  push:
    branches: 
     - main
jobs:
  check-macos:
    strategy:
      matrix:
        os: [macos-10.15, macos-11, macos-12, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Check Install Script
        run: static/script/install.sh
      - name: Check KCL run
        run: export PATH=$PATH:/usr/local/kclvm/bin && sudo kcl hello.k && sudo kcl hello.k --target native

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-go@v1
        with:
          go-version: "1.18"

      - name: Check Python Installation
        run: python3 -m pip install kclvm --user -U && python3 -m kclvm hello.k

      - name: Check Go Installation
        run: go install kusionstack.io/kclvm-go/cmds/kcl-go@main && $HOME/go/bin/kcl-go run hello.k

  check-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check Install Script
        run: static/script/install.sh
      - name: Check KCL run
        run: export PATH=$PATH:/usr/local/kclvm/bin && python3 -m pip install kclvm --user -U && kcl hello.k && kcl hello.k --target native

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-go@v1
        with:
          go-version: "1.18"

      - name: Check Python Installation
        run: python3 -m pip install kclvm --user -U && python3 -m kclvm hello.k

      - name: Check Go Installation
        run: go install kusionstack.io/kclvm-go/cmds/kcl-go@main && $HOME/go/bin/kcl-go run hello.k

  check-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Check Install Script
        run: static/script/install.ps1
      - name: Check KCL run
        run: C:\kclvm\bin\kcl.exe hello.k && C:\kclvm\bin\kcl.exe hello.k --target native

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - uses: actions/setup-go@v1
        with:
          go-version: "1.18"

      - name: Check Python Installation
        run: python3 -m pip install kclvm --user -U && python3 -m kclvm hello.k

      - name: Check Go Installation
        run: go install kusionstack.io/kclvm-go/cmds/kcl-go@main && C:\Users\runneradmin\go\bin\kcl-go.exe run hello.k
